version: "3.8"

services:
  nginx:
    container_name: nginx               
    volumes:
      - wordpress:/var/www/html       # Mount the WordPress volume.
    networks:
      - inception                            
    depends_on:                             # New line, indicating not to start NGINX until WordPress has started.
      - wordpress
    build:
      context: requirements/nginx          
      dockerfile: Dockerfile                 
    env_file: .env                          
    ports:
      - "443:443"                            # Specify the port to be exposed to the local machine.
    restart: always                 

  mariadb:
    container_name: mariadb          
    networks:
      - inception                     
    build:
      context: requirements/mariadb    
      dockerfile: Dockerfile
      args:
        SQL_DATABASE: ${SQL_DATABASE}
        SQL_USER: ${SQL_USER}
        SQL_PASSWORD: ${SQL_PASSWORD}
        SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}             
    env_file: .env
    healthcheck:
      # test: [ "CMD", "ls"]
      test :  ["CMD-SHELL", "pidof mysqld"]
      start_period: 20s
      # start_interval: 10s
      interval: 20s
      timeout: 5s
      retries: 3                  
    volumes: 
      - mariadb:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"          


  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html         # Mount the WordPress volume.
    networks:
      - inception
    build:
      context: requirements/wordpress 
      dockerfile: Dockerfile
    depends_on:                             # WordPress will start only after MariaDB (otherwise, it won't be able to configure the database).
      mariadb:
        condition: service_healthy
        # restart: true
    restart: on-failure
    ports:
      - "9000:9000"

volumes:
  wordpress:
    driver: local                               # Here we store the volume locally.
    driver_opts:
      type: 'none'                          
      o: 'bind'
      device: '$HOME/data/wordpress'    # Where to store the folder on your local computer.

  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'                                
      device: '$HOME/data/mariadb'       # Where to store the folder on your local computer.

networks:
  inception:
    driver: bridge